import React, { useEffect, useRef, } from 'react'
import Head from 'next/head'
import styles from '../../styles/Home.module.css'

/**
 * @returns {Headers}
 */
const genHeaders = () => {
	return Object.assign(
		{ "Content-Type": "application/json" },
	)
}

const Home = () => {
  useEffect(() => { 
    fetch("https://auth.thinkmay.net/auth/client/0", {
      method: "GET",
      headers: genHeaders(),
    }).then((res) => {
      res.text().then((token) => {
        var remote = "remote.thinkmay.net"

        var width = window.innerWidth * 0.66;
        var height = width * window.innerHeight / window.innerWidth;
        window.open(`https://${remote}/?token=${token}`, 'newwindow', 
          `width=${width},height=${height},top=${((window.innerHeight - height) / 2)},left=${((window.innerWidth - width) / 2)}`);
      })
    }).catch((err) => {
      console.log(err);
    })

  }, [])

  return (
    <div className={styles.app}>
      <Head>
        <title>WebRTC remote viewer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  )
}

export default Home
