"use client"

import { Analytics } from '@vercel/analytics/react';
import { GoogleAnalytics } from 'nextjs-google-analytics';
import * as React from 'react';


function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html>
			<head>
				<title>WebRTC remote viewer</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"
				></meta>
				<link rel="icon" href="/favicon.ico" />
			</head>
			<body>
			<GoogleAnalytics trackPageViews />
            <Analytics />
				<main>
					{children}
				</main>
			</body>
		</html>
	);
}

export default RootLayout;